// packages/create-electron/playground/solid-ts/src/renderer/src/components/Versions.tsx
import { type Component, createSignal } from 'solid-js'

const Versions: Component = () => {
  const [versions] = createSignal(window.electron.process.versions)

  return (
    <ul class="versions">
      <li class="electron-version">Electron v{versions().electron}</li>
      <li class="chrome-version">Chromium v{versions().chrome}</li>
      <li class="node-version">Node v{versions().node}</li>
      <li class="v8-version">V8 v{versions().v8}</li>
    </ul>
  )
}

export default Versions

// packages/create-electron/playground/react/src/renderer/src/components/Versions.jsx
import { useState } from 'react'

function Versions() {
  const [versions] = useState(window.electron.process.versions)

  return (
    <ul className="versions">
      <li className="electron-version">Electron v{versions.electron}</li>
      <li className="chrome-version">Chromium v{versions.chrome}</li>
      <li className="node-version">Node v{versions.node}</li>
      <li className="v8-version">V8 v{versions.v8}</li>
    </ul>
  )
}

export default Versions
