// packages/create-electron/playground/vue/src/renderer/src/components/Versions.vue
<script setup>
import { reactive } from 'vue'

const versions = reactive({ ...window.electron.process.versions })
</script>

<template>
  <ul class="versions">
    <li class="electron-version">Electron v{{ versions.electron }}</li>
    <li class="chrome-version">Chromium v{{ versions.chrome }}</li>
    <li class="node-version">Node v{{ versions.electron }}</li>
    <li class="v8-version">V8 v{{ versions.node }}</li>
  </ul>
</template>

// packages/create-electron/template/react-ts/src/renderer/src/components/Versions.tsx
import { useState } from 'react'

function Versions(): JSX.Element {
  const [versions] = useState(window.electron.process.versions)

  return (
    <ul className="versions">
      <li className="electron-version">Electron v{versions.electron}</li>
      <li className="chrome-version">Chromium v{versions.chrome}</li>
      <li className="node-version">Node v{versions.electron}</li>
      <li className="v8-version">V8 v{versions.node}</li>
    </ul>
  )
}

export default Versions
